### ISSUE TITLE
KULLANICI SİLİNECEK

### ISSUE THREAD

**Issue by Buralp86** [electropsycho/ODM.Web#10]
Kübra Karak | | İlköğretim Matematik | Fatih Ortaokulu | admin | 24.09.2019

Merve KUZAN | | İlköğretim Matematik | Ali Baran Numanoğlu Ortaokulu | admin | 25.09.2019
arkadaşları sistemden silelim şifre oluşturamıyor

**Comment by hkngln** [comment]
Sistemden herhangi bir kullanıcı silmeye gerek yoktur e posta adresleri doğru olduğu sürece tekrar tekrar şifre oluşturma mail'i alabilirler.
