### ISSUE TITLE
Değerlendirmedeki Soru Sayısı

### ISSUE THREAD

**Issue by anilake** [electropsycho/ODM.Web#12]
Değerlendirmedeki Soru Sayısına tıklayınca sorular aşağıda listelensin.

**Comment by anilake** [comment]
Havuzdaki ve toplam soru sayısında da aynı durum olsun. Bunu admin görebilsin.

**Comment by hkngln** [comment]
Bu sorun soru listeleme ekranına koyulan süzdürme seçenekleri ile çözülmüştür

![image](https://user-images.githubusercontent.com/5780826/87856693-66936800-c929-11ea-9bc0-f1d15531b672.png)
