### ISSUE TITLE
Değerlendiriciler

### ISSUE THREAD

**Issue by anilake** [electropsycho/ODM.Web#17]
Türkçe-Emine Merve Türkmen Kılıç
Türkçe- Ramazan Ökçe

Matematik- Tekmile Atıcı
Matematik- Kübra Karak

Fen Bilgisi- Bilal Yıldırım
Fen Bilgisi- Mehmet Yorgancı

**Comment by anilake** [comment]
Fen Bilgisi-Mutlu Uluçam

**Comment by hkngln** [comment]
Bütün yetkilendirmeler yapıldı
