### ISSUE TITLE
Soru oluştur bölümü sınıf seviyesi seçimi branşa göre olabilir

### ISSUE THREAD

**Issue by Buralp86** [electropsycho/ODM.Web#2]
Soru oluştur bölümü sınıf seviyesi seçimi branşa göre olabilir. Örnek; ilköğretim matematik için 5-6-7-8 gibi.

**Comment by hkngln** [comment]
https://github.com/electropsycho/ODM.Web/commit/2e8597969da78c997dbc8bdb7bb14a69d8831169 Numaralı commit ile çözülmüştür
