### ISSUE TITLE
Sınav işlemleri Bakanık Sınavı oluşturma

### ISSUE THREAD

**Issue by anilake** [electropsycho/ODM.Web#21]
Bro bakanlık 11 ekime kadar bizden 10 Türkçe 5 için 10 Türkçe 6 için soru istiyor. Bu soruları biz sistemden çekmek istiyoruz. Bir modül açsan adı Bakanlık Modülü Olsa içine d 15 branşı tanımlasan. Biz soru listelede o sorunun üzerine geldiğimizde bakanlık modülüne göndere tıkladığımızda soru o modüle gitse ve bizim kendi havuzumuzda bulunmasa.

**Comment by hkngln** [comment]
Duplicate of #31
