### ISSUE TITLE
Soru Listeleme

### ISSUE THREAD

**Issue by anilake** [electropsycho/ODM.Web#22]
Soru listeleme modlününde sınıf seviyesi seçince sadece o sınıfın soruları ya da ders seçince sadece o dersin soruların sıralanması

**Comment by hkngln** [comment]
Bu sorun https://github.com/electropsycho/ODM.Web/commit/b6161a46e730e1d8cea01ec8dff106c3e70f77ed numaralı commit ile çözülmüştür.
