### ISSUE TITLE
Kazanım Güncelleme

### ISSUE THREAD

**Issue by ozgeersan87** [electropsycho/ODM.Web#25]
Kazanımları yanlış ekleme durumunda silme,düzeltme veya güncelleme butonu

**Comment by hkngln** [comment]
Kazanımlar silinemez ancak güncellenebilir

**Comment by ozgeersan87** [comment]
Günaydın Hakan Hocam
Ekteki dosyayı oluşturduk bugünkü toplantımızda, siz de incelerseniz bi
fikir alışverişi yapabiliriz.

Hakan GÜLEN <notifications@github.com>, 30 Kas 2019 Cmt, 21:58 tarihinde
şunu yazdı:
