### ISSUE TITLE
Soruların Havuza Düşme Sorunu

### ISSUE THREAD

**Issue by ozgeersan87** [electropsycho/ODM.Web#26]
2 hakem 4 puan vermesine rağmen soru, soru havuzuna düşmüyor.Havuza düşen sorunun künyesinde değerlendiricilerin ifadeleri yer almalı.

**Comment by hkngln** [comment]
Bu sorun https://github.com/electropsycho/ODM.Web/commit/b6161a46e730e1d8cea01ec8dff106c3e70f77ed numaralı commit ile çözülmüştür.
