### ISSUE TITLE
Din Kültürü Dersi Kazanım Listeleme Sorunu

### ISSUE THREAD

**Issue by ozgeersan87** [electropsycho/ODM.Web#27]
Din Kültürü ve Ahlak Bilgisi kazanımları tamamlanmıştır, ders odaklı kazanım listeleme yaparken  başında DK gibi kodlar olmadığından 5.1 kodunu ara dediğimde bütün derslerin 5.1 kazanımını listeliyor.

![a](https://user-images.githubusercontent.com/57701970/69517552-c3d34700-0f5d-11ea-9bb0-8114c44a0f01.png)

**Comment by hkngln** [comment]
Özge Hocam bu beklenen bir davranış 1. si siz admin yetkilisiniz tüm kazanımları listeleme hakkınız var 2. arama başlayan karaterlerle değil içeren karakterlerle yapılıyor

**Comment by ozgeersan87** [comment]
👍👍👍

25 Kas 2019 Pzt, saat 11:08 tarihinde Hakan GÜLEN <notifications@github.com>
şunu yazdı:
