### ISSUE TITLE
Soru Yazarları Sorularının Akıbetini Göremiyor

### ISSUE THREAD

**Issue by ozgeersan87** [electropsycho/ODM.Web#28]
Soru yazarları sisteme hangi sınıf ve kazanımlardan kaç soru yüklediklerini, sorularının değerlendirmeden kaç puan aldığını ve sorularının havuza düşüp düşmediğini göremiyorlar.

**Comment by hkngln** [comment]
Bu sorun https://github.com/electropsycho/ODM.Web/commit/b6161a46e730e1d8cea01ec8dff106c3e70f77ed numaralı commit işlemi ile çözülmüştür.
