### ISSUE TITLE
Soru oluştur sekmesi kazanım arama sekmesine örn: arama şekli eklenebilir

### ISSUE THREAD

**Issue by Buralp86** [electropsycho/ODM.Web#3]
Soru oluştur sekmesi kazanım arama sekmesine örn: arama şekli eklenebilir

**Comment by hkngln** [comment]
Daha ayrıntılı ve açıklayıcı olursa sevinirim

**Comment by Buralp86** [comment]
Soru oluşturma seçeneğine girdiğimizde arama sekmesine örn: seçeneği ile aramanın nasıl yapılacağı açıklama yazılabilir.

**Comment by Buralp86** [comment]
soru oluştur arama sekmesinde açıklayıcı bir kelime olabilir; aramanın nasıl yapılacağı hakkında.
