### ISSUE TITLE
Soru Silmede yabancıl anahtar hatası ortaya çıkıyor

### ISSUE THREAD

**Issue by ozgeersan87** [electropsycho/ODM.Web#34]
Soru silme istekleri modülünde soru  silme talep edilen soru sil veya onayla denildiğinde soru listele modülüne tekrar düşüyor, soru silinmiyor.

**Comment by hkngln** [comment]
Evet soru silme onayında aşağıdaki hata ortaya çıkıyor 

> 1451 Cannot delete or update a parent row: a foreign key constraint fails (`o5000q46qj9tkh4ad`.`question_eval_requests`, CONSTRAINT `question_eval_requests_question_id_foreign` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`)) (SQL: delete from `questions` where `id` = 68)

değerlendirme isteği almış veya revizyon almış sorular için öncelikle revizyonlar ve değ. istekleri silinmeli bunu kod tarafında ben halledeceğim

**Comment by hkngln** [comment]
#40
