### ISSUE TITLE
Değerlendirici atama ekranında branşlar da görünmeli

### ISSUE THREAD

**Issue by ozgeersan87** [electropsycho/ODM.Web#35]
Değerlendirici atarken Kullanıcı İsimlerinin yanında branşları da görünsün veya soruya göre süzülüp ilgili dersin öğretmenleri görünsün

**Comment by hkngln** [comment]
İlgili sorunun bağlı olduğu dersin değerlendiricleri listeleniyor zaten farklı branşlar arasında değerlendirmeci listelenmiyor

**Comment by hkngln** [comment]
#38
