### ISSUE TITLE
Tasarım ihtiyacı olan ve olmayan sorular ayrıştırılmalı

### ISSUE THREAD

**Issue by ozgeersan87** [electropsycho/ODM.Web#37]
Yükleme 1 amatör yükleme (çizimi yapılmamış soru), Yükleme 2 profesyonel yükleme(indesign yüklemesi )

**Comment by hkngln** [comment]
İki ayrı yükleme ekranı gereksiz olur onun yerine yükleme ekranında bir seçenek daha eklemek yeterli gelecektir.

**Comment by hkngln** [comment]
https://github.com/electropsycho/ODM.Web/commit/35ac7136d14d8b3dc9f42cefc305b712fd695acf numaralı commit ile düzeltilmiştir.
