### ISSUE TITLE
Değerlendirici Atamasında Türkçe ve TDE branşlarıdan değerlendiriciler seçilebilmeli

### ISSUE THREAD

**Issue by ozgeersan87** [electropsycho/ODM.Web#38]
Tüm branşların değerlendiricilerine Türkçe ve Türk Dili ve Edebiyatı branşlarının da eklenmesi
Değerlendirici ekranında ismin yanında branşın da  görülmesinin soruların redaksiyon hatalarının giderilmesi için yararlı olacağı düşünülmektedir

**Comment by hkngln** [comment]
Bu sorun https://github.com/electropsycho/ODM.Web/commit/f65f437859e09f06a9cb2a8683fc69cd818effaf numaralı commit ile çözüldü
