### ISSUE TITLE
Şifremi unuttum sayfası

### ISSUE THREAD

**Issue by selimbaykose83** [electropsycho/ODM.Web#39]
şifremi unuttum sayfasında captcha hata veriyor, sanırım main.js den kaynaklı ve il ödm ismi nevşehir olarak çıkıyor

**Comment by hkngln** [comment]
Bu sayfadaki sorun https://github.com/electropsycho/ODM.Web/commit/6af00a8560ebd47bea5bd5da65641083ab5df18e kodlu commit ile çözülmüştür.
