### ISSUE TITLE
Soru silme isteği hatası

### ISSUE THREAD

**Issue by selimbaykose83** [electropsycho/ODM.Web#40]
Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`o38007z55v5hop2ff`.`question_eval_requests`, CONSTRAINT `que

silme isteğinde hata oluşuyordu

**Comment by hkngln** [comment]
Bu hata https://github.com/electropsycho/ODM.Web/commit/6af00a8560ebd47bea5bd5da65641083ab5df18e kodlu güncelleme ile giderilmiştir
