### ISSUE TITLE
Soru telif hakkı onayı

### ISSUE THREAD

**Issue by selimbaykose83** [electropsycho/ODM.Web#42]
Kullanıcı kayıt ekranında yada soru ekleme formunda sorunun tüm haklarının bakanlığıa ait olduğu ve başka bir yerde yayınlanmamış olduğunu ifade eden bir açıklamaya checbox ile kullacının onay vermesi istenebilir.

**Comment by hkngln** [comment]
@ #54 Sorunlar ile birlikte çözülecek
