### ISSUE TITLE
Değerlendirici Listeleme

### ISSUE THREAD

**Issue by ozgeersan87** [electropsycho/ODM.Web#43]
Değerlendiricilerin toplu şekilde görülebileceği bir listeye ihtiyacımız vardır. Yanlarında bilgileri olacak şekilde

**Comment by hkngln** [comment]
https://github.com/electropsycho/ODM.Web/commit/eda9dc21416e5e98d7e2b4a5a04bcd104423263a ile bu sorun çözülmüştür. Kullanıcı listeleme ekranından rol bazlı süzdürme yapılabilir.
