### ISSUE TITLE
Değerlendirmenin Sona Erdirilmesi

### ISSUE THREAD

**Issue by ozgeersan87** [electropsycho/ODM.Web#46]
Örneğin soru 4 hakeme gönderildi, 3 hakem değerlendirdi, 4. değerlendirmedi, hesapla ve bitir butonu eklenerek soru değerlendirme işlemini tamamlamalıyız.

**Comment by hkngln** [comment]
Mevcut yapıda manuel hesaplama var ancak aktif değil geliştirme planına alacağım lakin değerlendirici alt sayı sınırı var mı? Yani 3 kişi atandı ancak 2 kişi değerlendirme yaptı bu halde bile aktif olsun mu?

**Comment by hkngln** [comment]
ce7ea40 kodlu işleme(commit) ile manuel/elle hesaplama eklendi

![image](https://user-images.githubusercontent.com/5780826/87856623-f4228800-c928-11ea-80f7-58bff33ea789.png)
