### ISSUE TITLE
Ana Sayfa Ekranı

### ISSUE THREAD

**Issue by ozgeersan87** [electropsycho/ODM.Web#47]
Ana sayfa üzerinde değerlendirmedeki soru sayısı, sorulamayacak soru sayısı ve onaylanmış soru sayısı gibi renkli ekranlar üzerinden tıklama yapılarak ilgili başlığın sorularına toplu olarak ulaşsak.
Örneğin onaylanmış soru sayı ekranına tıkladığımda bütün onaylanmış soruları görebileyim.

**Comment by hkngln** [comment]
Soru listeleme ekranından süzdürme ile yapılabilir
