### ISSUE TITLE
Hakemlerin Yazdıklarını Soru Sahibi Göremiyor

### ISSUE THREAD

**Issue by anilake** [electropsycho/ODM.Web#48]
Soru sahibi sorusunun neden revizyona edildiğini göremedi.
Değerlendirilen soru ile değerlendirilecek soru arasında fark olmalı renklendirme olarak

**Comment by anilake** [comment]
Soru açıklaması kısmına değerlendiriciler açık ve uzun yazmak istiyor. Bir karakter sınırlaması olmaması iyi olur.

**Comment by hkngln** [comment]
> Soru sahibi sorusunun neden revizyona edildiğini göremedi.
> Değerlendirilen soru ile değerlendirilecek soru arasında fark olmalı renklendirme olarak


Mevcut değerlendirme tamamlanana kadar görülememesi normal
Renk tercihiniz ya da öneriniz var ise belirtiniz

**Comment by hkngln** [comment]
Bu sorun çözüldü
