### ISSUE TITLE
Değerlendirci Ataması sonrası mail gönderme

### ISSUE THREAD

**Issue by anilake** [electropsycho/ODM.Web#50]
Değerlendirici atadığımızda ona mail gitse. Bekleyen bir sorunuz var gibi..
Birde sisteme hakemeleri listele dediğimizde listelense, hakemlerin adı soyadı branşı vs. Kullanıcılı listeleme gibi

**Comment by hkngln** [comment]
Bu sorun https://github.com/electropsycho/ODM.Web/commit/f53b08a6b0864db59156358d1871ba0f9150c21f numaralı commit ile çözüldü
