### ISSUE TITLE
Soruların id'leri görünür olsa

### ISSUE THREAD

**Issue by selimbaykose83** [electropsycho/ODM.Web#52]
Soruların id'lerini de ekranda görebilsek çok iyi olur. Soruya başka zaman geri dönüş yapmak gerektiğinde bulması zor olabiliyor. id'sinden daha kolay bulunabilir. 

veya değerlendirilen soruların kodları soru listelemede görünürse o da işimize yarayabilir.

**Comment by selimbaykose83** [comment]
Birde daha önce yazıldı mı hatırlayamadım ama yönetici hesabındayken soru değerlendirme istekleri bölümünde soru yazarını da görebilir miyiz?

**Comment by hkngln** [comment]
![image](https://user-images.githubusercontent.com/5780826/80133560-1618a280-85a6-11ea-9154-56f45d0e77b1.png) url de görülen 80 sorunun id sini gösteriyor. Şimdilik bunu kapatıyorum halen ihtiyaç varsa tekrar açabilirsin
