### ISSUE TITLE
Turkce degerlendirici

### ISSUE THREAD

**Issue by selimbaykose83** [electropsycho/ODM.Web#55]
Sorulara degerlendirici atamasi yapilirken türkçe degerlendiricilerimiz tüm derslerde çıkıyor. Edebiyat için denememistim henüz. Sanirim son guncellemede türkçe ve edebiyat için düzenleme yapılmıştı.

**Comment by hkngln** [comment]
Türkçe ve Edebiyat öğretmenleri tüm sorulara redaksiyon amaçlı değerlendirici olarak iştirak edebilirler.
Şimdilik kapatıyorum bu sorunu. 👍
