### ISSUE TITLE
Soru Listeleme, açma ve geri dönüş için öneri

### ISSUE THREAD

**Issue by selimbaykose83** [electropsycho/ODM.Web#61]
Soru listele bölümünde soru listele denilip ders sınıf seviyesi vs seçilip filtrelendikten sonra sorular listeleniyor. Soruyu gördükten sonra geriye döndüğümüzde filtreler kalkmış oluyor. Bir ders, sınıftan soruları alırken bu tüm adımların tekrar edilmesine sebep oluyor. Geri dönüşte filtreler aynı kalabilir ya da sorular listelendikten sonra göster butonuna tıklarken sağ tık yeni sayfada göster (bunu yapamıyoruz şu an) aktif edilebilir.  Bu şekilde olması sistemi daha pratik hale getirebilir.

**Comment by hkngln** [comment]
Bu sorun vuex ile v1.1.0'da aşılacaktır

**Comment by hkngln** [comment]
Sağ tık ile yapılacak işlemi ayrı bir issue olarak daha detaylı anlatıp tekrar açabilirsiniz ancak yukarıdaki talebiniz 528c255bf8079087e01441f91f846bf8cf19d647 ile çözülmüştür
