### ISSUE TITLE
Kullanıcı kayıt oluşturma

### ISSUE THREAD

**Issue by selimbaykose83** [electropsycho/ODM.Web#63]
v1.0.0 sürümünde kullanıcı kayıt talebi oluşturduğunda kayıt talebiniz alınmıştır mesajı geldikten sonra yine kayıt formunda kalıyor ekran, login sayfasına yönlenebilir.

**Comment by hkngln** [comment]
Bu sorun ikiye bölünmüştür diğer kısım için https://github.com/electropsycho/ODM.Web/issues/64

**Comment by hkngln** [comment]
1352549a42b359c2993c28fe5bb169483a9dd1ba ile düzeltildi
