### ISSUE TITLE
Değerlendirici silince oluşan problem

### ISSUE THREAD

**Issue by selimbaykose83** [electropsycho/ODM.Web#66]
Örnek bir soruya 4 tane değerlendirici ataması yaptım. Daha sonra 2 değerlendirici soruyu değerlendirdi. Kalan 2 değerlendiriciyi de kaldırdım ve sistem burada error verdi. Soruya yeniden değerlendirici atanamıyor ve hatta soru artık gösterilemiyor, değerlendirme aşamasında kalıyor.

**Comment by hkngln** [comment]
Burada temel sorun kullanıcının değerlendirmeden sonra onu kapatmasıydı şu anda değerlendirme ekibi puan verse dahi kapatmıyoruz ta ki değerlendirme herkes için otomatik ya da elle bitirilene kadar değerlendirme tamamlandı ise o grubu tamamen kapatıyoruz v1.1.0 'da düzelecek bu hata

**Comment by hkngln** [comment]
19fcf59a7f43f546cf91402eb423a57039419af3 ile çözüldü ve daha sıkı bir kurallar bütünü getirildi min max değerlendirme ayarlara eklendi her soru için değerlendirme aşamasında puan hesaplanabilmesi için kaç geçerli puan olması gerektiği seçtirildi şu an sayamacağım ancak dağtım paketinde yer vereceğim bir çok değişiklik yapıldı
