### ISSUE TITLE
Minimum Gerekli Değerlendirme Sayısı ve Yöneticinin Soruyu Havuza Ekleme Yetkisi

### ISSUE THREAD

**Issue by unal77** [electropsycho/ODM.Web#67]
Sisteme eklenen sorulara 2 değerlendirici atadığımızda, değerlendiriciler puanlama yaptıktan sonra soru havuza düşmüyor ve o soru için başka değerlendirici atanamıyor. (Değerlendirici sayısı 3 olmamasından kaynaklı muhtemelen) 

Admin'e soruyu havuza ekleme yetkisi verilirse değerlendirici sayısı yetersiz branşlar için olumlu olacaktır.

**Comment by unal77** [comment]
Soru silme özelliğinde de hata alıyorum

**Comment by hkngln** [comment]
> Soru silme özelliğinde de hata alıyorum

İzinleriniz eksik muhtemelen sürüm notlarına tekrar bakmanızı tavsiye ediyorum

**Comment by hkngln** [comment]
Minimum puanlama yapması gerek değerlendirici sayısını her soru için değerlendirme aşamasında seçenekli yapmak istiyorum böylece  her soru için farklı sayıda gerekli değerlendirme sayısı değiştirilebilsin daha da parametrik ve esnek bir sistem olur diye düşünüyorum lütfen geri bildirim vermekten çekinmeyin

**Comment by unal77** [comment]
> > Soru silme özelliğinde de hata alıyorum
> 
> İzinleriniz eksik muhtemelen sürüm notlarına tekrar bakmanızı tavsiye ediyorum

pardon hocam sürüm notlarında yazıyormuş evet. Teşekkürler

**Comment by hkngln** [comment]
Yöneticinin soruyu doğrudan havuza ekleme yetkisi yeterince tartışılmadı topluluk genel bir kanaat orataya koyarsa ayrı bir konu başlığı olarak açabilirsiniz diğer sorunlar ise 19fcf59a7f43f546cf91402eb423a57039419af3 ile çözüldü
