### ISSUE TITLE
Şifremi Unuttum Hata Mesajı Veriyor. 

### ISSUE THREAD

**Issue by KarabukODM** [electropsycho/ODM.Web#68]
Otomasyonda dahil olan mail adresinin şifresini unuttum bölümünden yeni şifre gönderme isteğinde hata mesajı alıyorum. Şifre değişikliği mailime gelmiyor.  Bu durum güncellemeden sonra olmaya başladı.
Hata Mesajı : "Maalesef sunucu taraflı bir hata meydana geldi. Lütfen sistem yöneticinize başvurunuz." 
![Ekran Alıntısı](https://user-images.githubusercontent.com/72380488/95057385-c4e90f00-06fe-11eb-984a-486f5950bab4.JPG)

**Comment by hkngln** [comment]
Testini yapalım sayın hocam orada değişiklikler yaptık evet ama denendi normalde ancak gözden kaçan bir durum varsa çözelim takipteyim

**Comment by hkngln** [comment]
Lütfen sunucudaki .env dosyanızı kontrol edin mail şifre ve kullanıcı adı bilgilerini teyit edin zira Nevşehir'de yaptığımız denemede sıkıntı olmadığını gördük özel bir durum söz konusu olabilir sorun .env kaynaklı değilse lütfen irtibat kurun

**Comment by KarabukODM** [comment]
Teşekkürler hocam. Dediğiniz gibi env dosyasında google verdiği key şifresini yanlış yazdığımız içinmiş. Şimdi düzeldi.

**Comment by hkngln** [comment]
Sorununuzun çözülmesine sevindim şimdi bu sorunu kapatıyorum herhangi bir problemde(mevcutlar içinde yoksa 😉) yeni sorun açmaktan çekinmeyin. İyi çalışmalar...
