### ISSUE TITLE
Soru Değerlendirme Maili

### ISSUE THREAD

**Issue by ozgeersan87** [electropsycho/ODM.Web#71]
Soru değerlendirme isteği gönderirken kısa açıklama eklenmeli (örn: Sayın hocam, değerlendirme sisteminde ortalama puan 
1 ve 2 olursa soru kullanılamaz olacak.
3 olursa soru yazarına düzeltme için gönderilecek (düzeltilmesini isteğimiz yeri net yazalım) ve soru tekrar değerlendirilecek.
4 veya 5 puan olursa soru havuza girecek.
Sizlerden ricamız bu bilgileri göz önünde bulundurarak dikkatli bir şekilde değerlendirme yapmanizdir. Teşekkürler...)

**Comment by hkngln** [comment]
a0ed9f250076f9834b8f7f77144feeb3b23e5219 ile çözüldü
