### ISSUE TITLE
Soru Yüklemede KVKK metni

### ISSUE THREAD

**Issue by ozgeersan87** [electropsycho/ODM.Web#73]
Soru yüklerken sorumluluk alınmalı(kvk metni ile ilgili açılmış sorunu bulup oraya metin yaz örn: Bakanlığımız Ölçme, Değerlendirme ve Sınav Hizmetleri Genel Müdürlüğü ve ilimiz Ölçme Değerlendirme merkezi tarafından kullanılmak amacıyla hazırladığım soruya/sorulara ait metin, görsel, tablo, grafik, vb. inde herhangi bir telif hakkı ihlali olmadığını, Seçenekler dâhil, sorunun tamamıyla özgün, hiçbir yerde kullanılmamış ve kullanılmayacak olduğunu beyan ve kabul ederim.  )

**Comment by hkngln** [comment]
37f5fef53cf3d233a9efe7417c90b282b576cac3 ile çözüldü
